Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _VideoRentalShop.Data;
using _VideoRentalShop.Models;

namespace _VideoRentalShop.Controllers
{
    public class CustomersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public CustomersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Customers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Customer.ToListAsync());
        }

        // GET: Customers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // GET: Customers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Customers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CustomerId,FirstName,MiddleName,LastName,Sex,Email,PhoneNumber,Address,DateOfBirth,MembershipDate")] Customer customer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(customer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer.FindAsync(id);
            if (customer == null)
            {
                return NotFound();
            }
            return View(customer);
        }

        // POST: Customers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CustomerId,FirstName,MiddleName,LastName,Sex,Email,PhoneNumber,Address,DateOfBirth,MembershipDate")] Customer customer)
        {
            if (id != customer.CustomerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(customer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CustomerExists(customer.CustomerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(customer);
        }

        // GET: Customers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var customer = await _context.Customer
                .FirstOrDefaultAsync(m => m.CustomerId == id);
            if (customer == null)
            {
                return NotFound();
            }

            return View(customer);
        }

        // POST: Customers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var customer = await _context.Customer.FindAsync(id);
            if (customer != null)
            {
                _context.Customer.Remove(customer);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CustomerExists(int id)
        {
            return _context.Customer.Any(e => e.CustomerId == id);
        }
    }
}

Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _VideoRentalShop.Data;
using _VideoRentalShop.Models;

namespace _VideoRentalShop.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MoviesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> Index()
        {
            return View(await _context.Movie.ToListAsync());
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.MovieId == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MovieID,Title,Genre,Stock,ReleaseDate,Director,Description,RentalPrice")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("MovieID,Title,Genre,Stock,ReleaseDate,Director,Description,RentalPrice")] Movie movie)
        {
            if (id != movie.MovieId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.MovieId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .FirstOrDefaultAsync(m => m.MovieId == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movie.FindAsync(id);
            if (movie != null)
            {
                _context.Movie.Remove(movie);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.MovieId == id);
        }
    }
}

Controllers/RentalHeadersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using _VideoRentalShop.Data;
using _VideoRentalShop.Models;

namespace _VideoRentalShop.Controllers
{
    public class RentalHeadersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RentalHeadersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: RentalHeaders
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.RentalHeader
                .Include(r => r.Customer)
                .Include(rh => rh.RentalDetails)
                    .ThenInclude(rd => rd.Movie); 

            return View(await applicationDbContext.ToListAsync());
        }

        // GET: RentalHeaders/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rentalHeader = await _context.RentalHeader
                .Include(r => r.Customer)
                .Include(rh => rh.RentalDetails)
                    .ThenInclude(rd => rd.Movie)
                .FirstOrDefaultAsync(m => m.RentalHeaderId == id);
            if (rentalHeader == null)
            {
                return NotFound();
            }

            return View(rentalHeader);
        }

        // GET: RentalHeaders/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId");
            ViewData["Movies"] = new SelectList(_context.Movie, "MovieId", "Title");
            return View();
        }

        // POST: RentalHeaders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("RentalHeaderId,CustomerId,RentedDate,ReturnDate")] RentalHeader rentalHeader, List<int>? MovieIds)
        {
            if (ModelState.IsValid)
            {
                _context.Add(rentalHeader);
                await _context.SaveChangesAsync();

                if (MovieIds != null && MovieIds.Count > 0)
                {
                    foreach (var movieId in MovieIds)
                    {
                        var rentalDetail = new RentalDetail
                        {
                            RentalHeaderId = rentalHeader.RentalHeaderId,
                            MovieId = movieId,
                            Status = "Rented"
                        };
                        _context.RentalHeaderDetails.Add(rentalDetail);
                    }
                    await _context.SaveChangesAsync(); // Save RentalHeaderDetails
                }
                    return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "Address", rentalHeader.CustomerId);
            return View(rentalHeader);
        }

        // GET: RentalHeaders/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rentalHeader = await _context.RentalHeader
                .Include(r => r.RentalDetails!)
                .ThenInclude(d => d.Movie!)
                .FirstOrDefaultAsync(r => r.RentalHeaderId == id);
            if (rentalHeader == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId", rentalHeader.CustomerId);
            var movieList = _context.Movie.ToList();
            var selectedMovies = rentalHeader.RentalDetails?.Select(d => d.MovieId).ToList() ?? new List<int>();

            ViewData["MovieList"] = new SelectList(movieList, "MovieId", "Title");
            ViewBag.SelectedMovies = rentalHeader.RentalDetails?.Select(d => new { d.MovieId, d.Movie!.Title, d.Status }).ToList();
            return View(rentalHeader);
        }

        // POST: RentalHeaders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("RentalHeaderId,CustomerId,RentedDate,ReturnDate")] RentalHeader rentalHeader,  List<int> MovieIds, List<string> Statuses)
        {
            if (id != rentalHeader.RentalHeaderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var existingRental = await _context.RentalHeader
                         .Include(r => r.RentalDetails)
                         .FirstOrDefaultAsync(r => r.RentalHeaderId == id);

                    if (existingRental == null)
                    {
                        return NotFound();
                    }

                    // Update RentalHeader details
                    existingRental.CustomerId = rentalHeader.CustomerId;
                    existingRental.RentedDate = rentalHeader.RentedDate;
                    existingRental.ReturnDate = rentalHeader.ReturnDate;

                    // Remove old movie selections
                    _context.RentalHeaderDetails.RemoveRange(existingRental.RentalDetails);

                    // Add new movie selections with statuses
                    if (MovieIds != null && Statuses != null && MovieIds.Count == Statuses.Count)
                    {
                        for (int i = 0; i < MovieIds.Count; i++)
                        {
                            _context.RentalHeaderDetails.Add(new RentalDetail
                            {
                                RentalHeaderId = rentalHeader.RentalHeaderId,
                                MovieId = MovieIds[i],
                                Status = Statuses[i]
                            });
                        }
                    }
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RentalHeaderExists(rentalHeader.RentalHeaderId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId", rentalHeader.CustomerId);
            return View(rentalHeader);
        }

        // GET: RentalHeaders/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var rentalHeader = await _context.RentalHeader
                .Include(r => r.Customer)
                .FirstOrDefaultAsync(m => m.RentalHeaderId == id);
            if (rentalHeader == null)
            {
                return NotFound();
            }

            return View(rentalHeader);
        }

        // POST: RentalHeaders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var rentalHeader = await _context.RentalHeader.FindAsync(id);
            if (rentalHeader != null)
            {
                _context.RentalHeader.Remove(rentalHeader);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RentalHeaderExists(int id)
        {
            return _context.RentalHeader.Any(e => e.RentalHeaderId == id);
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VideoShopRentalMVC</title>
    <link rel="stylesheet" href="~/css/mycsstheme.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
    <style>
        /* Fully Transparent Sidebar */
        #sidebar {
            width: 250px;
            height: 100vh;
            position: fixed;
            top: 0;
            left: 0;
            background: rgba(255, 255, 255, 0.1); /* 100% Transparent */
            backdrop-filter: blur(20px); /* Glass Effect */
            padding-top: 20px;
            transition: all 0.3s;
            border-right: 1px solid rgba(255, 255, 255, 0.2);
        }

        #sidebar a {
            color: white;
            padding: 12px;
            display: block;
            text-decoration: none;
            border-radius: 5px;
            transition: background 0.3s, transform 0.2s;
        }

        #sidebar a:hover {
            background: rgba(255, 255, 255, 0.2);
            transform: scale(1.05);
        }

        #main-content {
            margin-left: 250px;
            padding: 20px;
            transition: margin-left 0.3s;
        }

        /* Sidebar Toggle Button */
        #sidebarCollapse {
            position: absolute;
            top: 10px;
            left: 260px;
            background: rgba(255, 255, 255, 0.1);
            color: white;
            border: none;
            padding: 10px;
            cursor: pointer;
            z-index: 1000;
            transition: all 0.3s;
            border-radius: 5px;
        }

        #sidebarCollapse:hover {
            background: rgba(255, 255, 255, 0.2);
        }

        /* Collapsed Sidebar */
        .collapsed-sidebar #sidebar {
            margin-left: -250px;
        }

        .collapsed-sidebar #main-content {
            margin-left: 0;
        }

        .collapsed-sidebar #sidebarCollapse {
            left: 10px;
        }
    </style>
</head>
<body>

    <!-- Sidebar -->
    <nav id="sidebar">
        <h3 class="text-center text-white">🎬 Video Shop</h3>
        <ul class="nav flex-column">
            <li class="nav-item">
                <a href="@Url.Action("Index", "Home")">🏠 Home</a>
            </li>

            @if (User.Identity!.IsAuthenticated)
            {
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Customers")">👥 Customers</a>
                </li>
                <li class="nav-item">
                    <a href="@Url.Action("Index", "Movies")">🎥 Movies</a>
                </li>
                <li class="nav-item">
                    <a href="#" class="dropdown-toggle" data-bs-toggle="collapse" data-bs-target="#rentalMenu">📦 Rentals</a>
                    <ul id="rentalMenu" class="collapse">
                        <li><a href="@Url.Action("Index", "RentalHeaders")">📜 Rental Headers</a></li>
                 
                    </ul>
                </li>
            }

            <li class="nav-item">
                <a href="@Url.Action("Privacy", "Home")">🔒 Privacy</a>
            </li>
        </ul>

        <div class="mt-auto text-center">
            @if (User.Identity.IsAuthenticated)
            {
                <p class="text-white small">What's up?, @User.Identity.Name</p>
                <a class="btn btn-danger w-100" href="@Url.Page("/Account/Logout", new { area = "Identity" })">🚪 Logout</a>
            }
            else
            {
                <a class="btn btn-warning w-100" href="@Url.Page("/Account/Login", new { area = "Identity" })">🔑 Login</a>
            }
        </div>
    </nav>

    <!-- Sidebar Toggle Button -->
    <button id="sidebarCollapse">☰</button>

    <!-- Main Content -->
    <div id="main-content">
        <main role="main" class="pb-3 animate__animated animate__fadeIn">
            @RenderBody()
        </main>
    </div>

    <footer class="text-center p-2 text-muted">
        &copy; 2025 - VideoShopRentalMVC - <a asp-controller="Home" asp-action="Privacy" class="text-decoration-none">Privacy</a>
    </footer>

    @* <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script> *@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        // Sidebar Toggle Functionality
        document.getElementById("sidebarCollapse").addEventListener("click", function () {
            document.body.classList.toggle("collapsed-sidebar");
        });
    </script>

    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>